<?php

$productsMainCategories = array(
                                'Chiens' => array(
                                                'Nourriture',
                                                'Hygiène et Soins', 
                                                'Accessoires', 
                                                'Jouets', 
                                                'Antiparasite'),
                                'Chats' => array(
                                                'Nourriture',
                                                'Hygiène et Soins', 
                                                'Accessoires', 
                                                'Jouets', 
                                                'Antiparasite'), 
                                'Poissons' => array(
                                                'Nourriture',
                                                'Filtration', 
                                                'Accessoires', 
                                                'Décoration', 
                                                'Antiparasite'), 
                                'Reptiles' => array(
                                                'Nourriture',
                                                'Hygiène et Soins', 
                                                'Accessoires', 
                                                'Jouets', 
                                                'Antiparasite'), 
                                'NAC' => array(
                                                'Nourriture',
                                                'Hygiène et Soins', 
                                                'Accessoires', 
                                                'Jouets', 
                                                'Antiparasite')
                                );


$petsProductsCategories = array(
                                'Nourriture',
                                'Hygiène et Soins', 
                                'Accessoires', 
                                'Jouets', 
                                'Antiparasite'
                                );


$tabCatsCategories = array(
                        'Croquettes',
                        'Boîtes et sachets',
                        'Aliments médicalisés & spécifiques',
                        'Friandises',
                        'Litière',
                        'Arbre à chat & griffoir',
                        'Antiparasitaires',
                        'Fontaine',
                        'distributeur & gamelle',
                        'Bac à litière & maison de toilette',
                        'Toilettage',
                        'soins & Feliway',
                        'Jouet et jeu',
                        'Chatière & filet de protection',
                        'Panier',
                        'lit & couverture',
                        'Cage de transport & collier',
                        'Compléments alimentaires',
                        'Aliments sans céréales',
                        'Spécial races',
                        'Spécial chaton',
                        'Chat stérilisé ou castré',
                        );

$tabDogsCategories = array(
                        'Croquettes',
                        'Aliments médicalisés & spécifiques',
                        'Friandises',
                        'Boîtes et sachets',
                        'Antiparasitaires',
                        'Cage et caisse de transport',
                        'Jouet',
                        'Laisse',
                        'harnais & collier',
                        'Toilettage et hygiène',
                        'Panier',
                        'coussin & couchage',
                        'Dressage et sport canin',
                        'Compléments alimentaires',
                        'Niche',
                        'barrière et parc',
                        'Gamelle et distributeur',
                        'Vêtements et protections',
                        'Aliments sans céréales',
                        'Spécial races',
                        'Spécial chiot',
                        );

$tabOfBrands = array(
                    "Acana",
                    "Alcott",
                    "Almo Nature",
                    "Animalis",
                    "Bab'in",
                    "Carnilove",
                    "Dog's Love",
                    "Edgard & Cooper",
                    "GimDog",
                    "Lily's Kitchen",
                    "Mhims",
                    "Natura Diet",
                    "Nutrivia",
                    "Orijen",
                    "Pro-Nutrition Flatazor",
                    "Schesir",
                    "Taste of the Wild",
                    "True Instinct",
                    "True Leaf",
                    "Vigor & Sage",
                    "Vitakraft",
                    "Wellness",
                    "Équilibre & Instinct",
                    "8in1",
                    "Advance",
                    "Advance Diet",
                    "Adventuros",
                    "Animal Lovers",
                    "Animalis Nature",
                    "Anka",
                    "Armitage",
                    "Beaphar",
                    "Best for your Friend",
                    "Beyond",
                    "Biofood",
                    "Bocados",
                    "Bubimex",
                    "Canichef BIO",
                    "Croc Pro",
                    "Dado",
                    "Dechra",
                    "Dentalife",
                    "Dingo",
                    "Dog Chow",
                    "Dr Dingo",
                    "Essentiel",
                    "Eukanuba", "Farmina",
                    "Felix",
                    "Flexima",
                    "Francodex",
                    "Good Boy",
                    "Greenies",
                    "HEALSTY",
                    "Hill's",
                    "Hill's Science Plan",
                    "Kerbl",
                    "KONG",
                    "Moments",
                    "Mooky", "Naoty",
                    "Nature's Variety",
                    "NatureBridge",
                    "Neo Lupus",
                    "Nutrichef",
                    "Nutrivet",
                    "Nutrivia Nature",
                    "Nutrivia Nature Plus",
                    "Nutrivia Original",
                    "Nutrivia Vet",
                    "Nutro",
                    "Paradisio",
                    "Pedigree",
                    "PetCooking",
                    "Pets Unlimited",
                    "PLUTOS",
                    "Pro Plan",
                    "Prozym",
                    "Rescue Pets",
                    "Rosewood",
                    "Royal Canin",
                    "Starmark",
                    "Terra Canis",
                    "Tomojo",
                    "Trixie",
                    "Tubidog",
                    "Vetoquinol",
                    "Virbac",
                    "Whimzees",
                    );


?>